### PR TITLE
Target node 20

### LINKED ISSUE #418: Update Node.js to 20
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Node.js 16 actions are deprecated.
Therefore, you need to update Node.js used in this Action to 20.

### PR DESCRIPTION
**Pull request by xt0rted**
Fixes #418

### CODE REVIEW

**Comment by massongit** [comment]
@xt0rted Thank you for creating this PR!
Will this take a long time to release?

**Comment by xt0rted** [comment]
@massongit I'm working on doing new releases for all of my tools/actions, so this should be released in the next day or two.

**Comment by sroebert** [comment]
Any update on this? Would be great if this gets merged in.

**Comment by walterheck** [comment]
Would also love to see this (and a few others) merged..

**Comment by DarkteK** [comment]
Hi @xt0rted ! Sorry to bother you but is there any update on this?
Btw: Any of the arguments are going to be different? Or everything will remain the same?

**Comment by massongit** [comment]
@xt0rted When will you release this PR?

**Pull request merged**
